name: Compile aglio Firmware
on:
  push:
    branches: [vial]
  pull_request:
    branches: [vial]
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install QMK CLI
        run: pip install qmk
      - name: Compile AGLIO VIAL (UF2)
        run: qmk compile -kb aglio -km vial -e UF2
      - name: Upload UF2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aglio-uf2
          path: aglio_vial.uf2 
